#ifndef SHARED_CONFIG_H
#define SHARED_CONFIG_H

#define MAX_DEVICES 32
#define MAX_ID_LEN 32
#define MAX_TYPE_LEN 16
#define MAX_PASSWORD_LEN 64
#define MAX_TOKEN_LEN 64
#define MAX_LINE_LEN 1024
#define MAX_JSON_LEN 1024
#define MAX_ACTION_LEN 16
#define MAX_ADDR_LEN 64
#define DEFAULT_PORT 8888
#define DEFAULT_BACKLOG 8
#define LOG_LINE_LEN 256

#endif  /* SHARED_CONFIG_H */
